apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.web.env.DB_HOST | quote }}

            - name: DB_NAME
              value: {{ .Values.mysql.database | quote }}

            - name: DB_USER
              value: {{ .Values.web.env.DB_USER | quote }}

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
